# Generated by Django 4.1.9 on 2023-06-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("number_guessing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberGuess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.FloatField()),
                ("guess", models.CharField(max_length=10)),
                ("is_correct", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Guess",
        ),
    ]
