# Generated by Django 4.1.9 on 2023-06-06 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("number_guessing", "0002_numberguess_delete_guess"),
    ]

    operations = [
        migrations.AddField(
            model_name="numberguess",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="numberguess",
            name="is_correct",
            field=models.BooleanField(),
        ),
    ]
