# Generated by Django 4.1.9 on 2023-06-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foss", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Заголовок",
                        max_length=255,
                        verbose_name="Заголовок (title)",
                    ),
                ),
                (
                    "nav",
                    models.CharField(
                        default="Название ссылки",
                        max_length=255,
                        verbose_name="Название ссылки",
                    ),
                ),
                (
                    "nav_position",
                    models.IntegerField(
                        default=0, verbose_name="Приоритет в навигации (0 - исключить)"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        default="", verbose_name="Основное содержание страницы"
                    ),
                ),
                (
                    "page_current_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата Записи"),
                ),
            ],
            options={
                "verbose_name": "Контент текущей страницы",
                "verbose_name_plural": "Уникальный контент страниц",
                "ordering": ("-nav_position",),
            },
        ),
    ]
