# Generated by Django 4.1.9 on 2023-06-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foss", "0002_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ("-nav_position",),
                "verbose_name": "Current page content",
                "verbose_name_plural": "Page content",
            },
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(default="", verbose_name="Page content"),
        ),
        migrations.AlterField(
            model_name="page",
            name="page_current_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Edition date"),
        ),
        migrations.AlterField(
            model_name="page",
            name="nav",
            field=models.CharField(default="href", max_length=255, verbose_name="href"),
        ),
        migrations.AlterField(
            model_name="page",
            name="nav_position",
            field=models.IntegerField(
                default=0, verbose_name="Nav prior. (0 - exclude)"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(
                default="SampleTitle", max_length=255, verbose_name="Page title"
            ),
        ),
    ]
