# Generated by Django 4.1.9 on 2023-06-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foss", "0003_alter_page_options_alter_page_page_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="page_current_date",
            new_name="current_date",
        ),
        migrations.AddField(
            model_name="page",
            name="stylesheet",
            field=models.TextField(
                default="main.css", verbose_name="stylesheet content"
            ),
        ),
    ]
