# Generated by Django 4.1.9 on 2023-06-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foss", "0004_rename_page_current_date_page_current_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="form_type",
            field=models.TextField(default="", verbose_name="form type"),
        ),
        migrations.AddField(
            model_name="page",
            name="has_form",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="javascript",
            field=models.TextField(default="", verbose_name="javascript"),
        ),
    ]
