# Generated by Django 4.1.9 on 2023-06-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foss", "0005_page_form_type_page_has_form_page_javascript"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="form_type",
            field=models.TextField(
                default="", max_length=255, verbose_name="form type"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="javascript",
            field=models.TextField(
                default="", max_length=255, verbose_name="javascript"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="stylesheet",
            field=models.TextField(
                default="main.css", max_length=255, verbose_name="stylesheet content"
            ),
        ),
    ]
