# Generated by Django 4.1.9 on 2023-06-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foss", "0006_alter_page_form_type_alter_page_javascript_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="form_type",
            field=models.TextField(
                blank=True, default="", max_length=255, verbose_name="form type"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="javascript",
            field=models.TextField(
                blank=True, default="", max_length=255, verbose_name="javascript"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="stylesheet",
            field=models.TextField(
                blank=True,
                default="main.css",
                max_length=255,
                verbose_name="stylesheet content",
            ),
        ),
    ]
