# Generated by Django 4.1.9 on 2023-06-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foss", "0007_alter_page_form_type_alter_page_javascript_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="header",
            field=models.CharField(
                blank=True,
                default="SampleHeader",
                max_length=255,
                verbose_name="Page header",
            ),
        ),
    ]
