# Generated by Django 4.1.9 on 2023-06-07 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foss", "0008_page_header"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ("-nav_position",),
                "verbose_name": "New Page",
                "verbose_name_plural": "Page content",
            },
        ),
    ]
