# Generated by Django 4.1.9 on 2023-06-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foss", "0009_alter_page_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="LatexFormula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="LaTeX Header"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=1024, verbose_name="LaTeX Header"
                    ),
                ),
                (
                    "formula",
                    models.CharField(
                        blank=True, max_length=1024, verbose_name="LaTeX Header"
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
        ),
    ]
