# Generated by Django 4.1.9 on 2023-06-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foss", "0010_latexformula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="latexformula",
            name="description",
            field=models.TextField(
                blank=True, max_length=1024, verbose_name="LaTeX Description"
            ),
        ),
        migrations.AlterField(
            model_name="latexformula",
            name="formula",
            field=models.TextField(
                blank=True, max_length=1024, verbose_name="LaTeX Formula"
            ),
        ),
        migrations.AlterField(
            model_name="latexformula",
            name="header",
            field=models.CharField(max_length=255, verbose_name="LaTeX Header"),
        ),
    ]
