# Generated by Django 4.1.9 on 2023-06-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foss", "0011_alter_latexformula_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header",
                    models.CharField(max_length=255, verbose_name="Code Header"),
                ),
                (
                    "code",
                    models.TextField(
                        blank=True, max_length=1024, verbose_name="LaTeX Formula"
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        blank=True,
                        default="python",
                        max_length=255,
                        verbose_name="Code Header",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
        ),
    ]
