# Generated by Django 4.1.9 on 2023-06-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foss", "0012_codeexample"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programm_name",
                    models.CharField(max_length=255, verbose_name="Programm Name"),
                ),
                (
                    "icon_path",
                    models.TextField(
                        blank=True, max_length=1024, verbose_name="Icon Path"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="python",
                        max_length=255,
                        verbose_name="Description",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="codeexample",
            name="code",
            field=models.TextField(blank=True, max_length=1024, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="codeexample",
            name="lang",
            field=models.CharField(
                blank=True,
                default="python",
                max_length=255,
                verbose_name="Programming Language",
            ),
        ),
    ]
