# Generated by Django 4.1.9 on 2023-06-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foss", "0013_softexample_alter_codeexample_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="softexample",
            name="link",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Link"
            ),
        ),
    ]
