# Generated by Django 4.1.9 on 2023-06-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foss", "0014_softexample_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="codeexample",
            name="show",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
